-- Run this once in Supabase Dashboard > SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null default 'ลูกค้า',
  email text,
  phone text default '',
  address text default '',
  default_payment text not null default 'bank' check (default_payment in ('bank', 'card', 'wallet')),
  role text not null default 'customer' check (role in ('customer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null check (price >= 0),
  category text not null,
  image_url text not null,
  stock integer not null default 0 check (stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  user_id uuid references public.profiles(id) on delete set null,
  buyer text not null,
  contact text not null,
  address text not null,
  payment text not null,
  subtotal integer not null check (subtotal >= 0),
  discount_amount integer not null default 0 check (discount_amount >= 0),
  shipping_fee integer not null default 0 check (shipping_fee >= 0),
  coupon text,
  coupon_label text,
  total integer not null check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  name text not null,
  price integer not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  image_url text
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select coalesce((select role = 'admin' from public.profiles where id = auth.uid()), false);
$$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, username, display_name, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'username', ''), split_part(new.email, '@', 1)),
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)),
    new.email
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "profiles read self or admin" on public.profiles for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "profiles update self" on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));
create policy "products read" on public.products for select to anon, authenticated using (true);
create policy "products admin write" on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "orders read own or admin" on public.orders for select to authenticated using (user_id = auth.uid() or public.is_admin());
create policy "orders admin delete" on public.orders for delete to authenticated using (public.is_admin());
create policy "items read own or admin" on public.order_items for select to authenticated using (public.is_admin() or exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

-- Creates an order and decrements inventory in one transaction.
create or replace function public.create_order(payload jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare order_id uuid := gen_random_uuid(); item jsonb; current_stock integer;
begin
  if auth.uid() is null then raise exception 'Please sign in before checkout'; end if;
  for item in select * from jsonb_array_elements(payload -> 'items') loop
    select stock into current_stock from public.products where id = (item ->> 'id')::bigint for update;
    if current_stock is null or current_stock < (item ->> 'qty')::integer then raise exception 'สินค้าในคลังมีไม่เพียงพอ'; end if;
  end loop;
  insert into public.orders (id, order_number, user_id, buyer, contact, address, payment, subtotal, discount_amount, shipping_fee, coupon, coupon_label, total)
  values (order_id, payload ->> 'orderId', auth.uid(), payload ->> 'buyer', payload ->> 'contact', payload ->> 'address', payload ->> 'payment', (payload ->> 'subtotal')::integer, (payload ->> 'discountAmount')::integer, (payload ->> 'shippingFee')::integer, payload ->> 'coupon', payload ->> 'couponLabel', (payload ->> 'total')::integer);
  for item in select * from jsonb_array_elements(payload -> 'items') loop
    update public.products set stock = stock - (item ->> 'qty')::integer where id = (item ->> 'id')::bigint;
    insert into public.order_items (order_id, product_id, name, price, quantity, image_url)
    values (order_id, (item ->> 'id')::bigint, item ->> 'name', (item ->> 'price')::integer, (item ->> 'qty')::integer, item ->> 'img');
  end loop;
  return order_id;
end;
$$;

revoke all on function public.create_order(jsonb) from public;
grant execute on function public.create_order(jsonb) to authenticated;

-- Promote your first signed-up account to administrator, then replace the email:
-- update public.profiles set role = 'admin' where email = 'you@example.com';
