-- Run after 20260717_product_details.sql in Supabase Dashboard > SQL Editor.
create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  stock integer not null default 0 check (stock >= 0),
  unique (product_id, size)
);

alter table public.orders add column if not exists status text not null default 'pending' check (status in ('pending', 'paid', 'packing', 'shipped', 'completed', 'cancelled'));
alter table public.orders add column if not exists tracking_number text;
alter table public.order_items add column if not exists variant_id bigint references public.product_variants(id) on delete set null;

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.coupons (
  code text primary key,
  label text not null,
  type text not null check (type in ('percent', 'shipping')),
  value integer not null default 0 check (value >= 0),
  minimum_order integer not null default 0 check (minimum_order >= 0),
  expires_at timestamptz,
  usage_limit integer,
  used_count integer not null default 0 check (used_count >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Convert existing sizes into stock records. The old total is distributed across its sizes.
insert into public.product_variants (product_id, size, stock)
select p.id, sized.size,
  floor(p.stock / greatest(cardinality(p.sizes), 1))::integer +
  case when sized.position <= p.stock % greatest(cardinality(p.sizes), 1) then 1 else 0 end
from public.products p
cross join lateral unnest(coalesce(nullif(p.sizes, '{}'), array['One size'])) with ordinality as sized(size, position)
on conflict (product_id, size) do nothing;

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

alter table public.product_variants enable row level security;
alter table public.favorites enable row level security;
alter table public.coupons enable row level security;

create policy "variants read" on public.product_variants for select to anon, authenticated using (true);
create policy "variants admin write" on public.product_variants for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "favorites own" on public.favorites for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "coupons read active" on public.coupons for select to anon, authenticated using (active = true or public.is_admin());
create policy "coupons admin write" on public.coupons for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "orders admin update" on public.orders for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "public product image read" on storage.objects for select using (bucket_id = 'product-images');
create policy "admin product image write" on storage.objects for insert to authenticated with check (bucket_id = 'product-images' and public.is_admin());
create policy "admin product image update" on storage.objects for update to authenticated using (bucket_id = 'product-images' and public.is_admin());
create policy "admin product image delete" on storage.objects for delete to authenticated using (bucket_id = 'product-images' and public.is_admin());

insert into public.coupons (code, label, type, value, minimum_order, active)
values ('SAVE10', 'ส่วนลด 10%', 'percent', 10, 0, true), ('FREESHIP', 'ส่งฟรี', 'shipping', 0, 0, true)
on conflict (code) do nothing;

create or replace function public.create_order(payload jsonb)
returns uuid language plpgsql security definer set search_path = public as $$
declare order_id uuid := gen_random_uuid(); item jsonb; current_stock integer; coupon_row public.coupons%rowtype; subtotal_value integer := (payload ->> 'subtotal')::integer; discount_value integer := 0; shipping_value integer := 60; total_value integer;
begin
  if auth.uid() is null then raise exception 'Please sign in before checkout'; end if;
  if payload ->> 'coupon' is not null then
    select * into coupon_row from public.coupons where code = upper(payload ->> 'coupon') and active = true for update;
    if not found or (coupon_row.expires_at is not null and coupon_row.expires_at < now()) or (coupon_row.usage_limit is not null and coupon_row.used_count >= coupon_row.usage_limit) or subtotal_value < coupon_row.minimum_order then
      raise exception 'คูปองไม่สามารถใช้งานได้';
    end if;
    if coupon_row.type = 'percent' then discount_value := round(subtotal_value * coupon_row.value / 100.0); end if;
    if coupon_row.type = 'shipping' then shipping_value := 0; end if;
  end if;
  if subtotal_value = 0 then shipping_value := 0; end if;
  total_value := greatest(0, subtotal_value - discount_value + shipping_value);
  for item in select * from jsonb_array_elements(payload -> 'items') loop
    if item ->> 'variantId' is not null then
      select stock into current_stock from public.product_variants where id = (item ->> 'variantId')::bigint for update;
    else
      select stock into current_stock from public.products where id = (item ->> 'id')::bigint for update;
    end if;
    if current_stock is null or current_stock < (item ->> 'qty')::integer then raise exception 'ไซซ์สินค้าที่เลือกมีไม่เพียงพอ'; end if;
  end loop;
  insert into public.orders (id, order_number, user_id, buyer, contact, address, payment, subtotal, discount_amount, shipping_fee, coupon, coupon_label, total)
  values (order_id, payload ->> 'orderId', auth.uid(), payload ->> 'buyer', payload ->> 'contact', payload ->> 'address', payload ->> 'payment', subtotal_value, discount_value, shipping_value, coupon_row.code, coupon_row.label, total_value);
  for item in select * from jsonb_array_elements(payload -> 'items') loop
    if item ->> 'variantId' is not null then update public.product_variants set stock = stock - (item ->> 'qty')::integer where id = (item ->> 'variantId')::bigint; end if;
    update public.products set stock = greatest(0, stock - (item ->> 'qty')::integer) where id = (item ->> 'id')::bigint;
    insert into public.order_items (order_id, product_id, variant_id, name, price, quantity, size, image_url)
    values (order_id, (item ->> 'id')::bigint, nullif(item ->> 'variantId', '')::bigint, item ->> 'name', (item ->> 'price')::integer, (item ->> 'qty')::integer, item ->> 'size', item ->> 'img');
  end loop;
  if coupon_row.code is not null then update public.coupons set used_count = used_count + 1 where code = coupon_row.code; end if;
  return order_id;
end;
$$;
