-- Run once after 20260717_store_advanced.sql.
-- This migration adds payment-proof, product reviews, customer notifications,
-- and product attributes used by the improved storefront.

alter table public.products add column if not exists color text not null default '';
alter table public.orders add column if not exists payment_proof_path text;
alter table public.orders add column if not exists payment_note text;

create table if not exists public.product_reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  reviewer_name text not null,
  rating integer not null check (rating between 1 and 5),
  comment text not null default '' check (char_length(comment) <= 800),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, user_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'order',
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_at_idx on public.notifications (user_id, created_at desc);

alter table public.product_reviews enable row level security;
alter table public.notifications enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'product_reviews' and policyname = 'reviews public read') then
    create policy "reviews public read" on public.product_reviews for select to anon, authenticated using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notifications' and policyname = 'notifications own read') then
    create policy "notifications own read" on public.notifications for select to authenticated using (user_id = auth.uid() or public.is_admin());
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'notifications' and policyname = 'notifications own update') then
    create policy "notifications own update" on public.notifications for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

insert into storage.buckets (id, name, public)
values ('payment-slips', 'payment-slips', false)
on conflict (id) do update set public = false;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'payment proof upload own') then
    create policy "payment proof upload own" on storage.objects for insert to authenticated
      with check (bucket_id = 'payment-slips' and (storage.foldername(name))[1] = auth.uid()::text);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'payment proof read own or admin') then
    create policy "payment proof read own or admin" on storage.objects for select to authenticated
      using (bucket_id = 'payment-slips' and ((storage.foldername(name))[1] = auth.uid()::text or public.is_admin()));
  end if;
end $$;

create or replace function public.submit_product_review(payload jsonb)
returns public.product_reviews language plpgsql security definer set search_path = public as $$
declare
  result public.product_reviews;
  product_key bigint := (payload ->> 'productId')::bigint;
  score integer := (payload ->> 'rating')::integer;
  review_text text := trim(coalesce(payload ->> 'comment', ''));
  display_name text;
begin
  if auth.uid() is null then raise exception 'กรุณาเข้าสู่ระบบก่อนรีวิว'; end if;
  if score is null or score < 1 or score > 5 then raise exception 'กรุณาให้คะแนน 1 ถึง 5 ดาว'; end if;
  if not exists (
    select 1 from public.orders o
    join public.order_items oi on oi.order_id = o.id
    where o.user_id = auth.uid() and oi.product_id = product_key and coalesce(o.status, 'pending') <> 'cancelled'
  ) then raise exception 'รีวิวได้เฉพาะสินค้าที่เคยสั่งซื้อแล้ว'; end if;
  select display_name into display_name from public.profiles where id = auth.uid();
  insert into public.product_reviews (product_id, user_id, reviewer_name, rating, comment)
  values (product_key, auth.uid(), coalesce(display_name, 'ลูกค้า'), score, review_text)
  on conflict (product_id, user_id) do update set rating = excluded.rating, comment = excluded.comment, updated_at = now()
  returning * into result;
  return result;
end;
$$;

create or replace function public.submit_payment_proof(order_number_input text, proof_path text, proof_note text default '')
returns void language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'กรุณาเข้าสู่ระบบก่อนแนบหลักฐาน'; end if;
  if not exists (select 1 from public.orders where order_number = order_number_input and user_id = auth.uid()) then
    raise exception 'ไม่พบคำสั่งซื้อของคุณ';
  end if;
  update public.orders
  set payment_proof_path = proof_path, payment_note = trim(coalesce(proof_note, ''))
  where order_number = order_number_input and user_id = auth.uid();
  insert into public.notifications (user_id, kind, title, message)
  values (auth.uid(), 'payment', 'ส่งหลักฐานการชำระเงินแล้ว', 'เราได้รับหลักฐานของออเดอร์ ' || order_number_input || ' แล้ว กำลังรอตรวจสอบ');
end;
$$;

create or replace function public.notify_order_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.user_id is null then return new; end if;
  if tg_op = 'INSERT' then
    insert into public.notifications (user_id, kind, title, message)
    values (new.user_id, 'order', 'รับคำสั่งซื้อแล้ว', 'ออเดอร์ ' || new.order_number || ' ถูกสร้างเรียบร้อยแล้ว');
  elsif old.status is distinct from new.status then
    insert into public.notifications (user_id, kind, title, message)
    values (new.user_id, 'order', 'ออเดอร์อัปเดตสถานะ', 'ออเดอร์ ' || new.order_number || ' เปลี่ยนเป็น: ' ||
      case new.status when 'pending' then 'รอชำระเงิน' when 'paid' then 'ชำระแล้ว' when 'packing' then 'กำลังแพ็ก' when 'shipped' then 'จัดส่งแล้ว' when 'completed' then 'สำเร็จ' when 'cancelled' then 'ยกเลิก' else new.status end);
  end if;
  return new;
end;
$$;

drop trigger if exists order_change_notification on public.orders;
create trigger order_change_notification after insert or update of status on public.orders
for each row execute procedure public.notify_order_change();

revoke all on function public.submit_product_review(jsonb) from public;
grant execute on function public.submit_product_review(jsonb) to authenticated;
revoke all on function public.submit_payment_proof(text, text, text) from public;
grant execute on function public.submit_payment_proof(text, text, text) to authenticated;
